### ISSUE TITLE
Autoptimize integration

### ISSUE THREAD

**Issue by 2aces** [2aces/sunny#8]
Enable @futtta Autoptimize integration: when @autoptimize cache is purged, purge CloudFlare zone as well.

**Comment by futtta** [comment]
well, assuming sunny has a function called `sunny_purge_cloudflare`, you can simply hook into AO's cache being purged by doing;

`add_action( 'autoptimize_action_cachepurged', 'sunny_purge_cloudflare' );`

**Comment by futtta** [comment]
Had a look at Sunny's code, I _think_ (but did not test) something like this will work.

``` php
add_action( 'autoptimize_action_cachepurged', 'sunny_purge_cloudflare_for_ao' );
function sunny_purge_cloudflare_for_ao {
  if (@is_callable(array("Sunny_Purger","purge_cloudflare_cache_all"))) {
    $sunny_says=Sunny_Purger::purge_cloudflare_cache_all;
    // check $sunny_says for wp_error and handle that 
  }
}
```
